// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BridgePort() {
  return window['go']['main']['App']['BridgePort']();
}

export function Command(arg1) {
  return window['go']['main']['App']['Command'](arg1);
}

export function DiscoverLocalTGent() {
  return window['go']['main']['App']['DiscoverLocalTGent']();
}

export function GetLocalTGentAccess() {
  return window['go']['main']['App']['GetLocalTGentAccess']();
}

export function GetLocalTGentPassword() {
  return window['go']['main']['App']['GetLocalTGentPassword']();
}

export function HideQuake() {
  return window['go']['main']['App']['HideQuake']();
}

export function NextEvent() {
  return window['go']['main']['App']['NextEvent']();
}

export function OpenSettings() {
  return window['go']['main']['App']['OpenSettings']();
}

export function PulseTerminalSurface() {
  return window['go']['main']['App']['PulseTerminalSurface']();
}

export function ReadClipboardImage() {
  return window['go']['main']['App']['ReadClipboardImage']();
}

export function ReadTerminalClipboard() {
  return window['go']['main']['App']['ReadTerminalClipboard']();
}

export function SaveClipboardImage() {
  return window['go']['main']['App']['SaveClipboardImage']();
}

export function SetQuakeEnabled(arg1) {
  return window['go']['main']['App']['SetQuakeEnabled'](arg1);
}

export function SetQuakeShortcut(arg1) {
  return window['go']['main']['App']['SetQuakeShortcut'](arg1);
}

export function ShowNormal() {
  return window['go']['main']['App']['ShowNormal']();
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function ToggleQuake() {
  return window['go']['main']['App']['ToggleQuake']();
}

export function UpdateQuakeSettings(arg1) {
  return window['go']['main']['App']['UpdateQuakeSettings'](arg1);
}

export function ValidateLocalTGent(arg1, arg2) {
  return window['go']['main']['App']['ValidateLocalTGent'](arg1, arg2);
}
