// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {quake} from '../models';

export function BridgePort():Promise<number>;

export function Command(arg1:string):Promise<string>;

export function DiscoverLocalTGent():Promise<main.LocalTGentDiscovery>;

export function GetLocalTGentAccess():Promise<main.LocalTGentAccess>;

export function GetLocalTGentPassword():Promise<string>;

export function HideQuake():Promise<quake.State>;

export function NextEvent():Promise<string>;

export function OpenSettings():Promise<void>;

export function PulseTerminalSurface():Promise<void>;

export function ReadClipboardImage():Promise<main.ClipboardImage>;

export function ReadTerminalClipboard():Promise<main.TerminalClipboard>;

export function SaveClipboardImage():Promise<string>;

export function SetQuakeEnabled(arg1:boolean):Promise<main.DesktopStatus>;

export function SetQuakeShortcut(arg1:string):Promise<main.DesktopStatus>;

export function ShowNormal():Promise<quake.State>;

export function Status():Promise<main.DesktopStatus>;

export function ToggleQuake():Promise<quake.State>;

export function UpdateQuakeSettings(arg1:quake.Settings):Promise<quake.State>;

export function ValidateLocalTGent(arg1:string,arg2:string):Promise<main.LocalTGentValidation>;
