import type { ITheme } from '@xterm/xterm'
import { storage } from './storage'

export interface ThemeDefinition {
  id: string
  name: string
  group: 'dark' | 'light'
  terminal: ITheme
  ui: Record<string, string>
}

const themes: ThemeDefinition[] = [
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    group: 'dark',
    terminal: {
      background: '#1a1b26',
      foreground: '#a9b1d6',
      cursor: '#c0caf5',
      selectionBackground: '#33467c',
      black: '#15161e',
      red: '#f7768e',
      green: '#9ece6a',
      yellow: '#e0af68',
      blue: '#7aa2f7',
      magenta: '#bb9af7',
      cyan: '#7dcfff',
      white: '#a9b1d6',
      brightBlack: '#414868',
      brightRed: '#f7768e',
      brightGreen: '#9ece6a',
      brightYellow: '#e0af68',
      brightBlue: '#7aa2f7',
      brightMagenta: '#bb9af7',
      brightCyan: '#7dcfff',
      brightWhite: '#c0caf5',
    },
    ui: {
      '--color-bg-page': '#030712',
      '--color-bg-surface': '#1f2937',
      '--color-bg-elevated': '#111827',
      '--color-bg-overlay': 'rgba(0, 0, 0, 0.50)',
      '--color-border': '#374151',
      '--color-border-subtle': 'rgba(255, 255, 255, 0.06)',
      '--color-text-primary': '#e5e7eb',
      '--color-text-secondary': '#9ca3af',
      '--color-text-muted': '#6b7280',
      '--color-term-bg': '#1a1b26',
      '--color-term-fg': '#a9b1d6',
      '--color-term-cursor': '#c0caf5',
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    group: 'dark',
    terminal: {
      background: '#282a36',
      foreground: '#f8f8f2',
      cursor: '#f8f8f2',
      selectionBackground: '#44475a',
      black: '#21222c',
      red: '#ff5555',
      green: '#50fa7b',
      yellow: '#f1fa8c',
      blue: '#bd93f9',
      magenta: '#ff79c6',
      cyan: '#8be9fd',
      white: '#f8f8f2',
      brightBlack: '#6272a4',
      brightRed: '#ff6e6e',
      brightGreen: '#69ff94',
      brightYellow: '#ffffa5',
      brightBlue: '#d6acff',
      brightMagenta: '#ff92df',
      brightCyan: '#a4ffff',
      brightWhite: '#ffffff',
    },
    ui: {
      '--color-bg-page': '#1e1f29',
      '--color-bg-surface': '#282a36',
      '--color-bg-elevated': '#343746',
      '--color-bg-overlay': 'rgba(0, 0, 0, 0.50)',
      '--color-border': '#44475a',
      '--color-border-subtle': 'rgba(255, 255, 255, 0.08)',
      '--color-text-primary': '#f8f8f2',
      '--color-text-secondary': '#bfbfbf',
      '--color-text-muted': '#6272a4',
      '--color-term-bg': '#282a36',
      '--color-term-fg': '#f8f8f2',
      '--color-term-cursor': '#f8f8f2',
    },
  },
  {
    id: 'one-dark',
    name: 'One Dark',
    group: 'dark',
    terminal: {
      background: '#282c34',
      foreground: '#abb2bf',
      cursor: '#528bff',
      selectionBackground: '#3e4451',
      black: '#1e2127',
      red: '#e06c75',
      green: '#98c379',
      yellow: '#d19a66',
      blue: '#61afef',
      magenta: '#c678dd',
      cyan: '#56b6c2',
      white: '#abb2bf',
      brightBlack: '#5c6370',
      brightRed: '#e06c75',
      brightGreen: '#98c379',
      brightYellow: '#d19a66',
      brightBlue: '#61afef',
      brightMagenta: '#c678dd',
      brightCyan: '#56b6c2',
      brightWhite: '#ffffff',
    },
    ui: {
      '--color-bg-page': '#1e2127',
      '--color-bg-surface': '#282c34',
      '--color-bg-elevated': '#2c313a',
      '--color-bg-overlay': 'rgba(0, 0, 0, 0.50)',
      '--color-border': '#3e4451',
      '--color-border-subtle': 'rgba(255, 255, 255, 0.07)',
      '--color-text-primary': '#abb2bf',
      '--color-text-secondary': '#8b929e',
      '--color-text-muted': '#5c6370',
      '--color-term-bg': '#282c34',
      '--color-term-fg': '#abb2bf',
      '--color-term-cursor': '#528bff',
    },
  },
  {
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    group: 'dark',
    terminal: {
      background: '#1e1e2e',
      foreground: '#cdd6f4',
      cursor: '#f5e0dc',
      selectionBackground: '#45475a',
      black: '#45475a',
      red: '#f38ba8',
      green: '#a6e3a1',
      yellow: '#f9e2af',
      blue: '#89b4fa',
      magenta: '#f5c2e7',
      cyan: '#94e2d5',
      white: '#bac2de',
      brightBlack: '#585b70',
      brightRed: '#f38ba8',
      brightGreen: '#a6e3a1',
      brightYellow: '#f9e2af',
      brightBlue: '#89b4fa',
      brightMagenta: '#f5c2e7',
      brightCyan: '#94e2d5',
      brightWhite: '#a6adc8',
    },
    ui: {
      '--color-bg-page': '#11111b',
      '--color-bg-surface': '#1e1e2e',
      '--color-bg-elevated': '#313244',
      '--color-bg-overlay': 'rgba(0, 0, 0, 0.50)',
      '--color-border': '#45475a',
      '--color-border-subtle': 'rgba(205, 214, 244, 0.08)',
      '--color-text-primary': '#cdd6f4',
      '--color-text-secondary': '#a6adc8',
      '--color-text-muted': '#6c7086',
      '--color-term-bg': '#1e1e2e',
      '--color-term-fg': '#cdd6f4',
      '--color-term-cursor': '#f5e0dc',
    },
  },
  {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    group: 'dark',
    terminal: {
      background: '#002b36',
      foreground: '#839496',
      cursor: '#839496',
      selectionBackground: '#073642',
      black: '#073642',
      red: '#dc322f',
      green: '#859900',
      yellow: '#b58900',
      blue: '#268bd2',
      magenta: '#d33682',
      cyan: '#2aa198',
      white: '#eee8d5',
      brightBlack: '#586e75',
      brightRed: '#cb4b16',
      brightGreen: '#586e75',
      brightYellow: '#657b83',
      brightBlue: '#839496',
      brightMagenta: '#6c71c4',
      brightCyan: '#93a1a1',
      brightWhite: '#fdf6e3',
    },
    ui: {
      '--color-bg-page': '#001e27',
      '--color-bg-surface': '#002b36',
      '--color-bg-elevated': '#073642',
      '--color-bg-overlay': 'rgba(0, 0, 0, 0.50)',
      '--color-border': '#073642',
      '--color-border-subtle': 'rgba(131, 148, 150, 0.12)',
      '--color-text-primary': '#839496',
      '--color-text-secondary': '#657b83',
      '--color-text-muted': '#586e75',
      '--color-term-bg': '#002b36',
      '--color-term-fg': '#839496',
      '--color-term-cursor': '#839496',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    group: 'dark',
    terminal: {
      background: '#2e3440',
      foreground: '#d8dee9',
      cursor: '#d8dee9',
      selectionBackground: '#434c5e',
      black: '#3b4252',
      red: '#bf616a',
      green: '#a3be8c',
      yellow: '#ebcb8b',
      blue: '#81a1c1',
      magenta: '#b48ead',
      cyan: '#88c0d0',
      white: '#e5e9f0',
      brightBlack: '#4c566a',
      brightRed: '#bf616a',
      brightGreen: '#a3be8c',
      brightYellow: '#ebcb8b',
      brightBlue: '#81a1c1',
      brightMagenta: '#b48ead',
      brightCyan: '#8fbcbb',
      brightWhite: '#eceff4',
    },
    ui: {
      '--color-bg-page': '#242933',
      '--color-bg-surface': '#2e3440',
      '--color-bg-elevated': '#3b4252',
      '--color-bg-overlay': 'rgba(0, 0, 0, 0.50)',
      '--color-border': '#3b4252',
      '--color-border-subtle': 'rgba(216, 222, 233, 0.08)',
      '--color-text-primary': '#d8dee9',
      '--color-text-secondary': '#a5b1c2',
      '--color-text-muted': '#4c566a',
      '--color-term-bg': '#2e3440',
      '--color-term-fg': '#d8dee9',
      '--color-term-cursor': '#d8dee9',
    },
  },
  {
    id: 'gruvbox-dark',
    name: 'Gruvbox Dark',
    group: 'dark',
    terminal: {
      background: '#282828',
      foreground: '#ebdbb2',
      cursor: '#ebdbb2',
      selectionBackground: '#504945',
      black: '#282828',
      red: '#cc241d',
      green: '#98971a',
      yellow: '#d79921',
      blue: '#458588',
      magenta: '#b16286',
      cyan: '#689d6a',
      white: '#a89984',
      brightBlack: '#928374',
      brightRed: '#fb4934',
      brightGreen: '#b8bb26',
      brightYellow: '#fabd2f',
      brightBlue: '#83a598',
      brightMagenta: '#d3869b',
      brightCyan: '#8ec07c',
      brightWhite: '#ebdbb2',
    },
    ui: {
      '--color-bg-page': '#1d2021',
      '--color-bg-surface': '#282828',
      '--color-bg-elevated': '#3c3836',
      '--color-bg-overlay': 'rgba(0, 0, 0, 0.50)',
      '--color-border': '#3c3836',
      '--color-border-subtle': 'rgba(235, 219, 178, 0.08)',
      '--color-text-primary': '#ebdbb2',
      '--color-text-secondary': '#a89984',
      '--color-text-muted': '#665c54',
      '--color-term-bg': '#282828',
      '--color-term-fg': '#ebdbb2',
      '--color-term-cursor': '#ebdbb2',
    },
  },
  {
    id: 'github-dark',
    name: 'GitHub Dark',
    group: 'dark',
    terminal: {
      background: '#0d1117',
      foreground: '#c9d1d9',
      cursor: '#58a6ff',
      selectionBackground: '#264f78',
      black: '#484f58',
      red: '#ff7b72',
      green: '#3fb950',
      yellow: '#d29922',
      blue: '#58a6ff',
      magenta: '#bc8cff',
      cyan: '#39c5cf',
      white: '#b1bac4',
      brightBlack: '#6e7681',
      brightRed: '#ffa198',
      brightGreen: '#56d364',
      brightYellow: '#e3b341',
      brightBlue: '#79c0ff',
      brightMagenta: '#d2a8ff',
      brightCyan: '#56d4dd',
      brightWhite: '#f0f6fc',
    },
    ui: {
      '--color-bg-page': '#010409',
      '--color-bg-surface': '#0d1117',
      '--color-bg-elevated': '#161b22',
      '--color-bg-overlay': 'rgba(0, 0, 0, 0.50)',
      '--color-border': '#30363d',
      '--color-border-subtle': 'rgba(240, 246, 252, 0.06)',
      '--color-text-primary': '#c9d1d9',
      '--color-text-secondary': '#8b949e',
      '--color-text-muted': '#6e7681',
      '--color-term-bg': '#0d1117',
      '--color-term-fg': '#c9d1d9',
      '--color-term-cursor': '#58a6ff',
    },
  },
  {
    id: 'github-light',
    name: 'GitHub Light',
    group: 'light',
    terminal: {
      background: '#ffffff',
      foreground: '#24292f',
      cursor: '#044289',
      selectionBackground: '#b6d4fe',
      black: '#24292f',
      red: '#cf222e',
      green: '#116329',
      yellow: '#4d2d00',
      blue: '#0969da',
      magenta: '#8250df',
      cyan: '#1b7c83',
      white: '#6e7781',
      brightBlack: '#57606a',
      brightRed: '#a40e26',
      brightGreen: '#1a7f37',
      brightYellow: '#633c01',
      brightBlue: '#218bff',
      brightMagenta: '#a475f9',
      brightCyan: '#3192aa',
      brightWhite: '#8c959f',
    },
    ui: {
      '--color-bg-page': '#f6f8fa',
      '--color-bg-surface': '#ffffff',
      '--color-bg-elevated': '#f6f8fa',
      '--color-bg-overlay': 'rgba(0, 0, 0, 0.30)',
      '--color-border': '#d0d7de',
      '--color-border-subtle': 'rgba(0, 0, 0, 0.08)',
      '--color-text-primary': '#24292f',
      '--color-text-secondary': '#57606a',
      '--color-text-muted': '#8c959f',
      '--color-term-bg': '#ffffff',
      '--color-term-fg': '#24292f',
      '--color-term-cursor': '#044289',
    },
  },
  {
    id: 'solarized-light',
    name: 'Solarized Light',
    group: 'light',
    terminal: {
      background: '#fdf6e3',
      foreground: '#657b83',
      cursor: '#586e75',
      selectionBackground: '#eee8d5',
      black: '#073642',
      red: '#dc322f',
      green: '#859900',
      yellow: '#b58900',
      blue: '#268bd2',
      magenta: '#d33682',
      cyan: '#2aa198',
      white: '#eee8d5',
      brightBlack: '#002b36',
      brightRed: '#cb4b16',
      brightGreen: '#586e75',
      brightYellow: '#657b83',
      brightBlue: '#839496',
      brightMagenta: '#6c71c4',
      brightCyan: '#93a1a1',
      brightWhite: '#fdf6e3',
    },
    ui: {
      '--color-bg-page': '#eee8d5',
      '--color-bg-surface': '#fdf6e3',
      '--color-bg-elevated': '#eee8d5',
      '--color-bg-overlay': 'rgba(0, 0, 0, 0.25)',
      '--color-border': '#d6cdb7',
      '--color-border-subtle': 'rgba(0, 0, 0, 0.08)',
      '--color-text-primary': '#586e75',
      '--color-text-secondary': '#657b83',
      '--color-text-muted': '#93a1a1',
      '--color-term-bg': '#fdf6e3',
      '--color-term-fg': '#657b83',
      '--color-term-cursor': '#586e75',
    },
  },
  {
    id: 'catppuccin-latte',
    name: 'Catppuccin Latte',
    group: 'light',
    terminal: {
      background: '#eff1f5',
      foreground: '#4c4f69',
      cursor: '#dc8a78',
      selectionBackground: '#ccd0da',
      black: '#5c5f77',
      red: '#d20f39',
      green: '#40a02b',
      yellow: '#df8e1d',
      blue: '#1e66f5',
      magenta: '#ea76cb',
      cyan: '#179299',
      white: '#acb0be',
      brightBlack: '#6c6f85',
      brightRed: '#d20f39',
      brightGreen: '#40a02b',
      brightYellow: '#df8e1d',
      brightBlue: '#1e66f5',
      brightMagenta: '#ea76cb',
      brightCyan: '#179299',
      brightWhite: '#bcc0cc',
    },
    ui: {
      '--color-bg-page': '#e6e9ef',
      '--color-bg-surface': '#eff1f5',
      '--color-bg-elevated': '#e6e9ef',
      '--color-bg-overlay': 'rgba(0, 0, 0, 0.25)',
      '--color-border': '#ccd0da',
      '--color-border-subtle': 'rgba(0, 0, 0, 0.08)',
      '--color-text-primary': '#4c4f69',
      '--color-text-secondary': '#6c6f85',
      '--color-text-muted': '#9ca0b0',
      '--color-term-bg': '#eff1f5',
      '--color-term-fg': '#4c4f69',
      '--color-term-cursor': '#dc8a78',
    },
  },
  {
    id: 'one-light',
    name: 'One Light',
    group: 'light',
    terminal: {
      background: '#fafafa',
      foreground: '#383a42',
      cursor: '#526fff',
      selectionBackground: '#bfceff',
      black: '#383a42',
      red: '#e45649',
      green: '#50a14f',
      yellow: '#c18401',
      blue: '#4078f2',
      magenta: '#a626a4',
      cyan: '#0184bc',
      white: '#a0a1a7',
      brightBlack: '#696c77',
      brightRed: '#e45649',
      brightGreen: '#50a14f',
      brightYellow: '#c18401',
      brightBlue: '#4078f2',
      brightMagenta: '#a626a4',
      brightCyan: '#0184bc',
      brightWhite: '#fafafa',
    },
    ui: {
      '--color-bg-page': '#e5e5e6',
      '--color-bg-surface': '#fafafa',
      '--color-bg-elevated': '#f0f0f1',
      '--color-bg-overlay': 'rgba(0, 0, 0, 0.25)',
      '--color-border': '#d4d4d5',
      '--color-border-subtle': 'rgba(0, 0, 0, 0.07)',
      '--color-text-primary': '#383a42',
      '--color-text-secondary': '#696c77',
      '--color-text-muted': '#a0a1a7',
      '--color-term-bg': '#fafafa',
      '--color-term-fg': '#383a42',
      '--color-term-cursor': '#526fff',
    },
  },
  {
    id: 'nord-light',
    name: 'Nord Light',
    group: 'light',
    terminal: {
      background: '#eceff4',
      foreground: '#2e3440',
      cursor: '#2e3440',
      selectionBackground: '#d8dee9',
      black: '#2e3440',
      red: '#bf616a',
      green: '#a3be8c',
      yellow: '#ebcb8b',
      blue: '#81a1c1',
      magenta: '#b48ead',
      cyan: '#88c0d0',
      white: '#d8dee9',
      brightBlack: '#4c566a',
      brightRed: '#bf616a',
      brightGreen: '#a3be8c',
      brightYellow: '#ebcb8b',
      brightBlue: '#81a1c1',
      brightMagenta: '#b48ead',
      brightCyan: '#8fbcbb',
      brightWhite: '#eceff4',
    },
    ui: {
      '--color-bg-page': '#d8dee9',
      '--color-bg-surface': '#eceff4',
      '--color-bg-elevated': '#e5e9f0',
      '--color-bg-overlay': 'rgba(0, 0, 0, 0.20)',
      '--color-border': '#c8ced8',
      '--color-border-subtle': 'rgba(0, 0, 0, 0.08)',
      '--color-text-primary': '#2e3440',
      '--color-text-secondary': '#4c566a',
      '--color-text-muted': '#7b88a1',
      '--color-term-bg': '#eceff4',
      '--color-term-fg': '#2e3440',
      '--color-term-cursor': '#2e3440',
    },
  },
  {
    id: 'gruvbox-light',
    name: 'Gruvbox Light',
    group: 'light',
    terminal: {
      background: '#fbf1c7',
      foreground: '#3c3836',
      cursor: '#3c3836',
      selectionBackground: '#d5c4a1',
      black: '#3c3836',
      red: '#cc241d',
      green: '#98971a',
      yellow: '#d79921',
      blue: '#458588',
      magenta: '#b16286',
      cyan: '#689d6a',
      white: '#7c6f64',
      brightBlack: '#928374',
      brightRed: '#9d0006',
      brightGreen: '#79740e',
      brightYellow: '#b57614',
      brightBlue: '#076678',
      brightMagenta: '#8f3f71',
      brightCyan: '#427b58',
      brightWhite: '#3c3836',
    },
    ui: {
      '--color-bg-page': '#ebdbb2',
      '--color-bg-surface': '#fbf1c7',
      '--color-bg-elevated': '#ebdbb2',
      '--color-bg-overlay': 'rgba(0, 0, 0, 0.25)',
      '--color-border': '#d5c4a1',
      '--color-border-subtle': 'rgba(0, 0, 0, 0.08)',
      '--color-text-primary': '#3c3836',
      '--color-text-secondary': '#504945',
      '--color-text-muted': '#928374',
      '--color-term-bg': '#fbf1c7',
      '--color-term-fg': '#3c3836',
      '--color-term-cursor': '#3c3836',
    },
  },
  {
    id: 'rose-pine-dawn',
    name: 'Rosé Pine Dawn',
    group: 'light',
    terminal: {
      background: '#faf4ed',
      foreground: '#575279',
      cursor: '#575279',
      selectionBackground: '#dfdad9',
      black: '#575279',
      red: '#b4637a',
      green: '#286983',
      yellow: '#ea9d34',
      blue: '#56949f',
      magenta: '#907aa9',
      cyan: '#d7827e',
      white: '#f2e9e1',
      brightBlack: '#797593',
      brightRed: '#b4637a',
      brightGreen: '#286983',
      brightYellow: '#ea9d34',
      brightBlue: '#56949f',
      brightMagenta: '#907aa9',
      brightCyan: '#d7827e',
      brightWhite: '#faf4ed',
    },
    ui: {
      '--color-bg-page': '#f2e9e1',
      '--color-bg-surface': '#faf4ed',
      '--color-bg-elevated': '#f2e9e1',
      '--color-bg-overlay': 'rgba(0, 0, 0, 0.20)',
      '--color-border': '#dfdad9',
      '--color-border-subtle': 'rgba(0, 0, 0, 0.06)',
      '--color-text-primary': '#575279',
      '--color-text-secondary': '#797593',
      '--color-text-muted': '#9893a5',
      '--color-term-bg': '#faf4ed',
      '--color-term-fg': '#575279',
      '--color-term-cursor': '#575279',
    },
  },
  {
    id: 'everforest-light',
    name: 'Everforest Light',
    group: 'light',
    terminal: {
      background: '#f3ead3',
      foreground: '#5c6a72',
      cursor: '#5c6a72',
      selectionBackground: '#e0dcc7',
      black: '#5c6a72',
      red: '#f85552',
      green: '#8da101',
      yellow: '#dfa000',
      blue: '#3a94c5',
      magenta: '#df69ba',
      cyan: '#35a77c',
      white: '#dfddc8',
      brightBlack: '#829181',
      brightRed: '#f85552',
      brightGreen: '#8da101',
      brightYellow: '#dfa000',
      brightBlue: '#3a94c5',
      brightMagenta: '#df69ba',
      brightCyan: '#35a77c',
      brightWhite: '#f3ead3',
    },
    ui: {
      '--color-bg-page': '#e5dfc6',
      '--color-bg-surface': '#f3ead3',
      '--color-bg-elevated': '#e5dfc6',
      '--color-bg-overlay': 'rgba(0, 0, 0, 0.20)',
      '--color-border': '#d4ccb0',
      '--color-border-subtle': 'rgba(0, 0, 0, 0.07)',
      '--color-text-primary': '#5c6a72',
      '--color-text-secondary': '#708089',
      '--color-text-muted': '#939f91',
      '--color-term-bg': '#f3ead3',
      '--color-term-fg': '#5c6a72',
      '--color-term-cursor': '#5c6a72',
    },
  },
]

const STORAGE_KEY = 'tgent_theme'

export async function loadThemeId(): Promise<string> {
  try {
    return (await storage.get(STORAGE_KEY)) || 'tokyo-night'
  } catch {
    return 'tokyo-night'
  }
}

export async function saveThemeId(id: string): Promise<void> {
  try {
    await storage.set(STORAGE_KEY, id)
  } catch {}
}

export function getTheme(id: string): ThemeDefinition {
  return themes.find(t => t.id === id) || themes[0]
}

export function getAllThemes(): ThemeDefinition[] {
  return themes
}

export function applyTheme(theme: ThemeDefinition): void {
  const style = document.documentElement.style
  for (const [key, value] of Object.entries(theme.ui)) {
    style.setProperty(key, value)
  }
  document.documentElement.dataset.colorScheme = theme.group
  document.documentElement.style.colorScheme = theme.group
  // 通知所有 Terminal 实例更新配色
  window.dispatchEvent(new CustomEvent('tgent-theme-change', { detail: theme }))
}
